#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker-compose -f ./deployment/docker/docker-compose-build.yml push
    edge-service discovery-service friend-service user-service recommendation-service