#!/bin/bash
docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
/usr/local/bin/docker-compose -f ./deployment/docker/docker-compose-build.yml push edge-service discovery-service friend-service user-service recommendation-service